### PR TITLE
Fix for #10 Add multilinesupport

### PR DESCRIPTION
**Pull request by JohannesDeml**
Adding multiline support for csv files on the basis of https://github.com/furukazu/UnityCSVReader
Streamlined the process so handling tsv files works the same way as importing csv files.

### CODE REVIEW

**Comment by skjalgsm** [comment]
This looks really good. A much cleaner approach than whats already there
too :) Thank you.

Only change I would like to see being made is that the method in the
TSVReader is not called ParseCSV but rather Parse since its not parsing a
CSV but a TSV. And the class name already gives that away. Similarily with
CSVReader, the method name should probably just be Parse there as well.

**Comment by JohannesDeml** [comment]
Oh, I totally missed that, thanks for pointing it out. I also included the scripts in the polyglot namespace, hope this fits the conventions now :)

**Comment by skjalgsm** [comment]
I'm getting three warnings in CsvReader.cs using Unity 5.4

Assets/Polyglot/Scripts/CsvTsvParser/CsvReader.cs(35,67): warning CS1692: Invalid number
Assets/Polyglot/Scripts/CsvTsvParser/CsvReader.cs(37,67): warning CS1692: Invalid number
Assets/Polyglot/Scripts/CsvTsvParser/CsvReader.cs(37,67): warning CS1691: `0' is not a valid warning number

Mind fixing those?

**Comment by skjalgsm** [comment]
I've tested the functionality and it seems good. Just annoying with warnings. Once you've fixed those I'll merge it in :)

**Comment by JohannesDeml** [comment]
Just tested it with 2018.2 since I didn't do anything fancy, but yeah totally makes sense. I will take a look at it this evening 👍

**Comment by JohannesDeml** [comment]
Hey again,

I first tried to get the same warning in Unity 5.6, but didn't get any warnings (apart from warnings from the main class which uses script dependant compilation).

When trying to get Unity 5.4 running I was not able to open the project or create a new one. I took a look at the lines referenced by you and I guess it is about a warning supression about a warning I didn't really find. Since I don't get any warnings, can you please check if the warning disappeared? :)

**Comment by JohannesDeml** [comment]
Here there,
would be sad if the PR would get forgotten since it adds quite useful functionality. Did you have the time to take a look at it?

**Comment by skjalgsm** [comment]
Agreed 🙂 Didn’t notice you had fixed the warnings. Thanks for reminding me. Great job on he PR 👍

**Comment by JohannesDeml** [comment]
Awesome, I'm happy I was able to contribute!

**Pull request merged**
