### PR TITLE
Localized String

### PR DESCRIPTION
**Pull request by Lawendt**
Implemented `Localized String` enabling the user to use localization on non-ui related things with the same inspector of `TextLocalized` components.

image

image

image

### CODE REVIEW

**Comment by skjalgsm** [comment]
if all you want to is reuse the inspector, wouldn't it be better to implement this as a Attribute?
https://docs.unity3d.com/ScriptReference/PropertyDrawer.html

**Comment by Lawendt** [comment]
I thought about doing an `Attribute` for strings where I used the field as the key and then I saw the parameters and decided to make it a struct just in case.
But I implemented it as an `PropertyDrawer`, changing it to an attribute would be easy. If you want I can do it!

**Comment by skjalgsm** [comment]
Yeah I think that would be way more useful than this because this makes it
hard to take an existing project and start using Polyglot. In my experience
developers usually add localization at the end and something like this
where you have to go through the project and swap out string with a new
type of object will make people not use the feature. But if they can just
add an attribute above it, then it will be so much more useful :)

**Comment by Lawendt** [comment]
@Skjalgsm I Implemented it as an attribute, but I didn't deleted the struct 'cause I think it is useful. I also made the struct to implict cast to string for easier use. If the user wants, they can just replace their strings with `LocalizedString` that it will probably have no refactoring needed in the rest of their code. 

Here an example of usage of both implementations: 

image

**Comment by Lawendt** [comment]
Hello?

**Pull request merged**
